#WIP
version: '3.5'
services:

  elearning-api:
    image: elearning/elearning-api
    restart: always
    build:
      context: ./
    container_name: elearning-api
    links:
      - elearning_mysql
    environment:
      - APP_PORT=3000
    ports:
      - "3012:3000"

  elearning_mysql:
    image: "mysql:5.7"
    container_name: elearning_mysql
    ports:
    - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=elearning-db
